# Advanced configuration file for ChunkLoader plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
  #Multi-language setting
  #Available: eng, kor
  language: "eng"

  update-check: "false"


command:
  #Name of main command
  #You can change this to be what you want
  name: "chunkloader"

  #Aliases of main command
  #You can add, replace, or remove them as you like
  aliases: ["cl", "chunkload"]

  children:
    #Setting of subcommands
    #Same as main command setting
    register:
      name: "Register"
      aliases: ["r", "add"]
    unregister:
      name: "Unregister"
      aliases: ["u", "remove"]
    list:
      name: "List"
      aliases: ["l"]


permission:
  #Permission of main command
  #You can change this to be what you want
  main: "op"

  children:
    #Permission of subcommands
    #Same as Permission of main command setting
    register: "op"
    unregister: "op"
    list: "op"